vulnerabilities:
  - id: CVE-2026-40200
    statement: Not Affected. musl. We don't accept EUC-KR encoded data in our services.
  - id: CVE-2026-34359
    expired_at: 2026-10-01
    statement: Not Affected. We don't use the HAPI Server.
  - id: CVE-2026-33180
    expired_at: 2026-10-01
    statement: Not Affected. We don't use the HAPI Server.
  - id: CVE-2026-45367
    expired_at: 2026-10-01
    statement: Not Affected. We don't us FHIR Path in this service.
  - id: CVE-2026-49485
    expired_at: 2026-10-01
    statement: Not Affected - We don't call the affected functionality.
  - id: CVE-2026-43869
    expired_at: 2026-10-01
    statement: Not Affected. Only the Apache Thirst Server is affected.
  - id: CVE-2026-55471
    expired_at: 2026-10-01
    statement: transform operations from XSL utilities are not used.
  - id: CVE-2026-14456
    expired_at: 2026-10-01
    statement: Not affected. We don't use QUIC as protocol.
  - id: CVE-2026-43871
    expired_at: 2026-10-01
    statement: DoS vulnerability (Infinite Loop) in Apache Thrift. Not Affected because not used in this service. fixable with futute hapi update
misconfigurations:
  - id: KSV011
    statement: Runs with UID <= 10000 - User is 10000 in Dockerfile too
  - id: KSV015
    statement: Runs with UID <= 10000 - User is 10000 in Dockerfile too
  - id: KSV016
    statement: Runs with UID <= 10000 - User is 10000 in Dockerfile too
  - id: KSV020
    statement: Runs with UID <= 10000 - User is 10000 in Dockerfile too
  - id: KSV021
    statement: Runs with UID <= 10000 - User is 10000 in Dockerfile too
  - id: KSV027
    statement: Non-default /proc masks set - Not detected by Trivy
  - id: KSV039
    statement: limit range usage
  - id: KSV040
    statement: resource quota usage
  - id: KSV110
    statement: False Positive Namespace coming from stage-config
# Ignore single packages is temporarily not supported from BaseImage
licenses:
  - id: GPL-2.0-only
  - id: GPL-2.0-or-later
  - id: LGPL-2.1-or-later
  - id: MPL-2.0
  - id: GPL-2.0-with-classpath-exception
